name: Dev Netlify CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing frontend...
        run: npm install

      - name: Testing frontend...
        run: npm run test

      - name: Building frontend...
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITLOG_A8FD9 }}"
          projectId: fitlog-a8fd9
