name: Prod Netlify CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing frontend...
        run: npm install

      - name: Testing frontend...
        run: npm run test

      - name: Building frontend...
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITLOG_A8FD9 }}"
          channelId: live
          projectId: fitlog-a8fd9
